#!/usr/bin/php
<?php

include 'Nefu.php';
include 'Wx.php';
$wxAppid  = 'wx00c21901537bc5a6';
$wxSecret = '821ab731206d8993146f3d151d6217b5';

$db = mysqli_connect('localhost:3306', 'root', 'GT338570');
$wx = new Wx($wxAppid, $wxSecret);
mysqli_select_db($db, 'nefuer');
$sql = '
	SELECT `user`.`acc`, `user`.`pwd`, `user`.`last_upd`, `wx_user`.`openid`
	FROM `user`, `wx_user`
	WHERE `user`.`acc` = `wx_user`.`acc` AND `wx_user`.`openid` <> "" AND `user`.`acc` = 2015214310
	LIMIT 10;
';
$result = mysqli_query($db, $sql);
for($i = 0, $len = mysqli_num_rows($result); $i < $len; $i++)
{
	$user = mysqli_fetch_row($result);
	if($user[2] > 0)
	{
		update_user($user);
	}
	else
	{
		record_user($user);
	}
}
mysqli_close($db);

function update_user($user)
{
	global $db;
	$wx_send = array();
	$upd_score = array();
	$scores = get_scores($user);
	if($scores === FALSE)
		return;
	$sql = '
		SELECT `id`, `lesson`, `type`, `score`
		FROM `score_record`
		WHERE `acc` = ' . $user[0];
	$scoresRes = mysqli_query($db, $sql);
	$scoresExt = array();
	for($i = 0, $len = mysqli_num_rows($scoresRes); $i < $len; $i++)
	{
		$scoresExt[] = mysqli_fetch_row($scoresRes);
	}
	$scoresExtLen = count($scoresExt);
	for($i = 0, $len = count($scores); $i < $len; $i++)
	{
		$ext = FALSE;
		for($j = 0; $j < $scoresExtLen; $j++)
		{
			if($scores[$i]['code'] == $scoresExt[$j][1] && $scores[$i]['type'] == $scoresExt[$j][2])
			{
				$ext = $j;
				break;
			}
		}
		if($ext === FALSE)
		{
			$wx_send[] = array('new', $scores[$i]);
			$upd_score[] = array('INSERT', $scores[$i]);
		}
		else
		{
			if($scores[$i]['score'] != $scoresExt[$ext][3])
			{
				$wx_send[] = array('update', $scores[$i]);
				$scores[$i]['id'] = $scoresExt[$ext][0];
				$upd_score[] = array('REPLACE', $scores[$i]);
			}
		}
	}
	$sqlInsert = '';
	$sqlReplace = '';
	for($i = 0, $iloop = count($upd_score); $i < $iloop; $i++)
	{
		if($upd_score[$i][0] == 'INSERT')
		{
			$sqlInsert .= '(' . $user[0] . ', "' . $upd_score[$i][1]['code'] . '", "' . $upd_score[$i][1]['type'] . '", "' . $upd_score[$i][1]['score'] . '"),';
		}
		else
		{
			$sqlReplace .= '(' . $upd_score[$i][1]['id'] . ', ' . $user[0] . ', "' . $upd_score[$i][1]['code'] . '", "' . $upd_score[$i][1]['type'] . '", "' . $upd_score[$i][1]['score'] . '"),';
		}
	}
	if($sqlInsert !== '')
	{
		$sql = 'INSERT INTO `score_record`(`acc`, `lesson`, `type`, `score`) VALUES' . substr($sqlInsert, 0, strlen($sqlInsert) - 1) . ';';
		mysqli_query($db, $sql);
	}
	if($sqlReplace !== '')
	{
		$sql = 'REPLACE INTO `score_record`(`id`, `acc`, `lesson`, `type`, `score`) VALUES' . substr($sqlReplace, 0, strlen($sqlReplace) - 1) . ';';
		mysqli_query($db, $sql);
	}

	global $wx;
	for($i = 0, $iloop = count($wx_send); $i < 0; $i++)
	{
		$msg_data = array(
			'first' => array(
				'value' => $wx_send[$i][0] == 'new' ? '最新成绩！' : '您有一个成绩有变化',
				'color' => ''
			),
			'keynote1' => array(
				'value' => $wxSecret[$i][1]['name'],
				'color' => '#173177'
			),
			'keynote2' => array(
				'value' => $wxSecret[$i][1]['type'],
				'color' => '#173177'
			),
			'keynote3' => array(
				'value' => $wxSecret[$i][1]['score'],
				'color' => '#173177'
			),
			'keynote4' => array(
				'value' => $wxSecret[$i][1]['num'],
				'color' => '#173177'
			),
			'remark' => array(
				'value' => '点击查看全部成绩',
				'color' => ''
			)
		);
		echo $wx->msgTemp($user[3], 'Zu1NRhwKYW1jsdmD9dE8ukK3g4iCwKzKFy_wlfROMZE', $msg_data, 'http://nefuer.jblog.info');
	}
}

function record_user($user)
{
	global $db;
	$scores = get_scores($user);
	if($scores === FALSE)
		return;
	$upd_score = array();
	for($i = 0, $len = count($scores); $i < $len; $i++)
	{
		$upd_score[] = $scores[$i];
	}
	$sqlInsert = '';
	for($i = 0, $iloop = count($upd_score); $i < $iloop; $i++)
	{
		$sqlInsert .= '(' . $user[0] . ', "' . $upd_score[$i]['code'] . '", "' . $upd_score[$i]['type'] . '", "' . $upd_score[$i]['score'] . '"),';
	}
	if($sqlInsert !== '')
	{
		$sql = 'INSERT INTO `score_record`(`acc`, `lesson`, `type`, `score`) VALUES' . substr($sqlInsert, 0, strlen($sqlInsert) - 1) . ';';
		mysqli_query($db, $sql);
	}
	$sql = '
		UPDATE `user`
		SET `last_upd` = ' . time() . '
		WHERE `acc` = ' . $user[0];
	mysqli_query($db, $sql);
}

function get_scores($user)
{
	$user = Nefu::getInstance($user[0], $user[1]);
	if($user === FALSE)
		return;
	$score = $user->userScore();
	$scores = array();
	for($i = 0, $iloop = count($score['all']); $i < $iloop; $i++)
	{
		$scores[] = array(
			'name' => $score['all'][$i]['name'],
        	'code' => $score['all'][$i]['code'],
            'type' => '总成绩',
            'score' => $score['all'][$i]['score'],
            'num' => $score['all'][$i]['num']
		);
	}
	for($i = 0, $iloop = count($score['item']); $i < $iloop; $i++)
	{
        if('' != $score['item'][$i]['s_1'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '阶段1',
                'score' => $score['item'][$i]['s_1'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_2'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '阶段2',
                'score' => $score['item'][$i]['s_2'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_3'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '阶段3',
                'score' => $score['item'][$i]['s_3'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_4'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '阶段4',
                'score' => $score['item'][$i]['s_4'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_5'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '阶段5',
                'score' => $score['item'][$i]['s_5'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_common'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '平时成绩',
                'score' => $score['item'][$i]['s_common'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_middle'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '期中',
                'score' => $score['item'][$i]['s_middle'],
                'num' => $score['item'][$i]['num']
            );
        if('' != $score['item'][$i]['s_final'])
            $scores[] = array(
            	'name' => $score['item'][$i]['name'],
            	'code' => $score['item'][$i]['code'],
                'type' => '期末',
                'score' => $score['item'][$i]['s_final'],
                'num' => $score['item'][$i]['num']
            );
    }
	return $scores;
}

?>